version: '3.8'

services:
    web:
        build: .
        command: runserver 0.0.0.0:8000
        volumes:
            - ./app/main:/usr/src/app/main
        ports:
            - 8000:8000
        env_file:
            - ./.env.dev

    db:
        image: postgres:15
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_DB=hello_django_dev
            - POSTGRES_USER=hello_django
            - POSTGRES_PASSWORD=hello_django

volumes:
    postgres_data: